In [0]:
from pyspark.sql import Row

birth_rdd = sc.textFile('/FileStore/tables/birth.txt')
birth_split = birth_rdd.map(lambda l : l.split("/"))
birth_row = birth_split.map(lambda x : Row (name = x[0], year = x[1], month = x[2], day = x[3], city = x[4]))

birth_df = sqlContext.createDataFrame(birth_row)
birth_df.show()

In [0]:
peopleDF = spark.read.parquet("/FileStore/tables/people-10m.parquet")

In [0]:
import pyspark.sql.functions as f

peopleDF.filter("salary <= 20000")\
        .withColumn("salary", f.abs(f.col("salary")))\
        .withColumn("new_salary", f.round(f.col("salary") * 1.1)).show(5)

In [0]:
import pyspark.sql.functions as f

peopleDF.filter("salary >= 30000")\
        .select(f.max("salary"), f.min("salary"), f.round(f.avg("salary")).alias("averageSalary")).show()

In [0]:
import pyspark.sql.functions as f

peopleDF.groupBy("lastName", 'gender')\
        .agg(f.count('salary').alias('count'), f.max('salary').alias('max salary'))\
        .show(5)

In [0]:
bikeSharingDayDF = (spark
                   .read
                   .option("inferSchema", "true")
                   .option("header", "true")
                   .csv("/mnt/training/bikeSharing/data-001/day.csv"))
bikeSharingDayDF.show(3)

In [0]:
databricksBlogDF = spark.read.json("/FileStore/tables/training/databricks_blog.json")
databricksBlogDF.show(5)

In [0]:
from pyspark.sql.functions import year

BlogDF2 = databricksBlogDF.select('authors', 'categories', 'creator', 'dates')\
                          .withColumn('publishedOn', year("dates.publishedOn"))
BlogDF2.show(3)

In [0]:
from pyspark.sql.functions import year, col, date_format

resultDF = databricksBlogDF.select('categories', 'creator', date_format('dates.publishedOn', "yyyy-MM-dd").alias('date'))\
                            .filter(year(col('date')) == '2013')\
                            .orderBy('date')
resultDF.show(3)

In [0]:
from pyspark.sql.functions import size, col, explode

databricksBlog2DF = databricksBlogDF.\
  select('title', 'authors', explode(col('authors')).alias('author')).\
  filter(size('authors') > 1).\
  orderBy('title')
databricksBlog2DF.show(5)